Feature/combobox implementation
dokedu/dokedu pull request #54
Opened 2024-02-05 16:28 UTC by benciks

Contains new select component that uses radix vue

closes #50

2024-02-10 15:06 UTC, tomhaerter commented
@benciks currently in draft, let me know when it's ready for review by changing its status

2024-02-12 18:01 UTC, benciks commented
@tomhaerter replaced dselect with combobox everywhere in dokedu. Please have a look, also at the code of the combobox itself. Let me know what you think.

2024-02-13 18:39 UTC, tomhaerter commented
<img width="589" alt="image" src="https://github.com/dokedu/dokedu/assets/16882922/eaae8591-5154-4c4f-bb61-19fa37407950">

2024-02-13 18:44 UTC, benciks commented
- Would still be better if v-model is an object and we customize rest of the app for it - In case an item isn't in option and then we reload etc.

2024-02-13 21:15 UTC, tomhaerter commented
Found the following regression

1. Navigate to `/record/reports/new`
2. Select `Alle` (all)
3. Close select
4. Click into it
5. Write the letter `e`
6. Combobox disappears

**Recording**

https://github.com/dokedu/dokedu/assets/16882922/d09c8f10-2bee-4054-9972-46c79bf206be

2024-02-13 21:16 UTC, tomhaerter requested changes
Found the following regression

1. Navigate to `/record/reports/new`
2. Select `Alle` (all)
3. Close select
4. Click into it
5. Write the letter `e`
6. Combobox disappears

**Recording**

https://github.com/dokedu/dokedu/assets/16882922/d09c8f10-2bee-4054-9972-46c79bf206be

2024-02-19 15:20 UTC, benciks commented
@tomhaerter Did the mentioned changes.

2025-04-08 09:35 UTC, closed without merging